import torch
import torch.nn.functional as F
from typing import List, Dict, Any, Optional
from torch_geometric.data import HeteroData

from modules.registry import register
from modules.base import BaseSelector
from models.gat_network import SchemaHeteroGAT
from modules.projectors.dual_tower import DualTowerProjector
from modules.encoders.token_encoder import TokenEncoder
from utils.logger import get_logger

logger = get_logger(__name__)

@register("selector", "GATClassifierSelector")
class GATClassifierSelector(BaseSelector):
    def __init__(self, weight_path: str, in_channels: int = 384, hidden_channels: int = 256, out_channels: int = 256, threshold: float = 0.5, **kwargs):
        super().__init__()
        self.device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
        self.threshold = threshold
        
        # 1. 분리된 아키텍처 초기화 (train_gat.py와 완벽히 동일하게)
        self.gat_model = SchemaHeteroGAT(
            in_channels=in_channels,
            hidden_channels=hidden_channels,
            out_channels=out_channels
        ).to(self.device)
        
        self.projector = DualTowerProjector(
            text_dim=in_channels,
            graph_dim=hidden_channels,
            joint_dim=hidden_channels
        ).to(self.device)
        
        self.encoder = TokenEncoder() # 질의(NLQ) 임베딩용
        
        # 2. Checkpoint 로드 및 검증
        logger.info(f"Loading Decoupled GAT & Projector weights from {weight_path}")
        checkpoint = torch.load(weight_path, map_location=self.device)
        
        if 'gat_state_dict' in checkpoint and 'projector_state_dict' in checkpoint:
            self.gat_model.load_state_dict(checkpoint['gat_state_dict'])
            self.projector.load_state_dict(checkpoint['projector_state_dict'])
            logger.info(f"✨ Weights loaded successfully! (Trained Epoch: {checkpoint.get('epoch', 'Unknown')}, Val Recall: {checkpoint.get('recall', 'Unknown'):.4f})")
        else:
            raise RuntimeError("Invalid checkpoint format. Ensure the weight file was generated by the latest train_gat.py")
        
        self.gat_model.eval()
        self.projector.eval()
        self.latest_scores = []
        
    def select(self, scores: Optional[List[float]], candidates: List[int], question: str, graph_data: HeteroData, metadata: Dict[str, Any], **kwargs) -> List[int]:
        """
        GAT와 Projector를 통과시켜 각 노드의 '확률값(Sigmoid)'을 추출합니다.
        여기서는 필터링(Pruning)을 하지 않고, PCST Extractor가 구조를 확장하며 
        Uncertainty Scaling을 직접 수행할 수 있도록 확률 점수 리스트만 전달합니다.
        """
        graph_data = graph_data.to(self.device)
        
        with torch.no_grad():
            # 1. 질의 임베딩
            encoded_output = self.encoder.encode([question])
            if isinstance(encoded_output, tuple):
                q_emb = encoded_output[0].to(self.device)
            else:
                q_emb = encoded_output.to(self.device)

            # [핵심 수정] 3차원 [Batch, Seq, Dim] 또는 2차원 [Seq, Dim] 텐서를 
            # 무조건 문장 전체를 대표하는 [1, Dim] 크기의 단일 벡터로 Mean Pooling
            if q_emb.dim() == 3:
                q_emb = q_emb.mean(dim=1) # [1, 22, 384] -> [1, 384]
            elif q_emb.dim() == 2 and q_emb.size(0) > 1:
                q_emb = q_emb.mean(dim=0, keepdim=True) # [22, 384] -> [1, 384]
            elif q_emb.dim() == 1:
                q_emb = q_emb.unsqueeze(0) # [384] -> [1, 384]
            
            # 2. GAT 통과 -> 구조적 위상이 반영된 노드 임베딩 추출
            node_embs_dict = self.gat_model(graph_data.x_dict, graph_data.edge_index_dict)
            
            num_nodes = len(metadata.get('node_metadata', {}))
            final_scores = torch.zeros(num_nodes, device=self.device)
            
            # 3. 노드 타입별 예측 확률(Sigmoid) 계산 및 평탄화 (Flatten)
            num_t = graph_data['table'].num_nodes
            num_c = graph_data['column'].num_nodes
            
            if num_t > 0:
                z_q_t, z_n_t = self.projector(q_emb, node_embs_dict['table'])
                logits_t = self.projector.compute_similarity(z_q_t, z_n_t)
                final_scores[0:num_t] = torch.sigmoid(logits_t).view(-1)
                
            if num_c > 0:
                z_q_c, z_n_c = self.projector(q_emb, node_embs_dict['column'])
                logits_c = self.projector.compute_similarity(z_q_c, z_n_c)
                final_scores[num_t:num_t+num_c] = torch.sigmoid(logits_c).view(-1)
                
            if 'fk_node' in node_embs_dict and node_embs_dict['fk_node'].size(0) > 0:
                num_fk = node_embs_dict['fk_node'].size(0)
                z_q_fk, z_n_fk = self.projector(q_emb, node_embs_dict['fk_node'])
                logits_fk = self.projector.compute_similarity(z_q_fk, z_n_fk)
                final_scores[num_t+num_c:num_t+num_c+num_fk] = torch.sigmoid(logits_fk).view(-1)

        # 파이프라인의 다음 단계(PCST)로 넘겨주기 위해 latest_scores 저장
        self.latest_scores = final_scores.cpu().tolist()
        
        # Uncertainty PCST 알고리즘이 점수들을 직접 저울질하도록 모든 노드를 후보로 반환
        return candidates